### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by demostars** [tomgross/pycloud#1]
Great job! 

But have you deleted this from pip distribution? Or maybe some other reason?

Cheer up!

Thanks!

**Comment by tomgross** [comment]
Hi @demostars this project never was on pypi. I use it locally and didn't expect anyone else would use it. I can make an alpha release though. The simple operations are stable. I use it in production for backup but the pcloud API is not completly implemented.

**Comment by demostars** [comment]
Well thanks！

**Comment by tomgross** [comment]
Done https://pypi.python.org/pypi/pcloud/1.0a2
