### ISSUE TITLE
Can't authenticate with 2-factor authentication enabled

### ISSUE THREAD

**Issue by MisterY** [tomgross/pycloud#12]
I'm not sure if 2-factor authentication is supported in the library but I can't seem to find a way to do that. 
Apparently the pCloud APIs do not support 2-factor authentication yet so this may need to wait for the implementation on their side.

**Comment by MisterY** [comment]
Some relevant info may be found in the [docs](https://docs.pcloud.com/methods/intro/authentication.html). No mention of the 2FA for the moment.

**Comment by tomgross** [comment]
Probably oauth can help here. The pcloud API supports it but it is not implemented for pycloud yet. PR welcome 😉

**Comment by MisterY** [comment]
Hm, I did not notice anywhere in the [docs](https://docs.pcloud.com/methods/intro/authentication.html) the support for two-factor authentication.
From what I know, OAuth is just about tokens and 3rd-party identification. It is not directly related to 2-factor authentication, which implies using a 2nd channel. 
If you have any pointers in that direction, I'd be happy to look into it. From what I've seen, Keepass2Android also cannot register an app with pCloud when 2-factor is enabled. This is an issue with pCloud, not the client apps. Could be the same issue here. They just added the 2-factor support so it could take some time to provide support for it everywhere.

**Comment by tomgross** [comment]
OAuth 2.0 support landed in pycloud but the 2nd factor is not requested on the code flow used to authorize (https://docs.pcloud.com/methods/oauth_2.0/authorize.html). Currently there is nothing the library could do, if pCloud itself does not support it.
