### ISSUE TITLE
Protocol: Binary vs HTTP/JSON

### ISSUE THREAD

**Issue by awehrfritz** [tomgross/pycloud#18]
Hi,

Thanks for this small and handy library. 

This is not really an issue at all, but rather a question to the developers who actually went through the process of implementing the API: So, I was long wondering what the difference between the "binary" [1] and the "HTTP/JSON" [2] protocol is? The description on https://docs.pcloud.com/ doesn't really make that clear (at least to me).

Does pycloud implement both? And do you have any experience in which one would be fast/better?

Thanks,
Armin

[1] https://docs.pcloud.com/protocols/binary_protocol/
[2] https://docs.pcloud.com/protocols/http_json_protocol/

**Comment by tomgross** [comment]
Hi @awehrfritz pycloud currently only supports HTTP / JSON and unfortunately I don't have experience with the binary protocol.
