### ISSUE TITLE
How to use the downloadfile method?

### ISSUE THREAD

**Issue by pscal67** [tomgross/pycloud#27]
Im able to upload files but i struggle to understand the downloadfile method.
Does anyone have a simple code example for downloading a file?

**Comment by tomgross** [comment]
The purpose of the `downloadfile`-method is to retrieve the metadata from a download (share) link. What you want probably is to download file contents, which can be achived by the file ops API (https://docs.pcloud.com/methods/fileops/index.html)

Here is a minimal example:
```
In [7]: pc.file_open(path='/somefile.txt', flags=api.O_CREAT)
Out[7]: {'result': 0, 'fd': 1, 'fileid': 2046546721}
In [8]: pc.file_size(fd=1)
Out[8]: {'result': 0, 'size': 238, 'offset': 0}
In [9]: pc.file_read(fd=1, count=238)
Out[9]: b'Some Content'
```

**Comment by qo4on** [comment]
How do you download multiple files? Run the same code in parallel for a list of paths? Or consistently? Is there a function that expects a list of paths or a list of `fileid`'s?

**Comment by monish0612** [comment]
Can someone help me download a file from Pcloud to my local directory? I have attached the code snippet. Please help ASAP. I have attached the screenshot. 
![Uploading 2022-11-10_184949.jpg…]()

**Comment by monish0612** [comment]
Code Snippet:

pc = PyCloud('emailid', 'password', endpoint='eapi')

pc.downloadfile(url="File Download Link", path="Local Directory")

**Comment by Umercia** [comment]
> The purpose of the `downloadfile`-method is to retrieve the metadata from a download (share) link. What you want probably is to download file contents, which can be achived by the file ops API (https://docs.pcloud.com/methods/fileops/index.html)
> 
> Here is a minimal example:
> 
> ```
> In [7]: pc.file_open(path='/somefile.txt', flags=api.O_CREAT)
> Out[7]: {'result': 0, 'fd': 1, 'fileid': 2046546721}
> In [8]: pc.file_size(fd=1)
> Out[8]: {'result': 0, 'size': 238, 'offset': 0}
> In [9]: pc.file_read(fd=1, count=238)
> Out[9]: b'Some Content'
> ```

Not sure it is possible now, since the last version of the [pcloud API](https://docs.pcloud.com/methods/file/) does not contain anymore 'file_read' and 'file_open' methods.
