### ISSUE TITLE
New pCloud API Server

### ISSUE THREAD

**Issue by qo4on** [tomgross/pycloud#29]
I use correct email and password but authentication fails. I tried 2 different pcloud accounts, all of them work in browser but do not work through PyCloud.
```
from pcloud import PyCloud
pc = PyCloud(myemail, mypassword)

  File "C:\Users\Asm\miniconda3\lib\site-packages\pcloud\api.py", line 47, in __init__
    self.auth_token = self.get_auth_token()
  File "C:\Users\Asm\miniconda3\lib\site-packages\pcloud\api.py", line 82, in get_auth_token
    raise (AuthenticationError)
pcloud.api.AuthenticationError
```
Windows 10 64, Python 3.7.7, pcloud 1.0a8 (pip install -U pcloud).
Debug log:
```
2020-07-04 15:42:54,431 pycloud  Doing request to https://api.pcloud.com/getdigest
2020-07-04 15:42:54,431 pycloud  Params: {}
2020-07-04 15:42:55,228 pycloud  Doing request to https://api.pcloud.com/userinfo
2020-07-04 15:42:55,228 pycloud  Params: {'getauth': 1, 'logout': 1, 'username': 'myemail@gmail.com', 'digest': 'pCloudpCloudpCloudZCyCuOpv68cIlKo537ZCa6vKmxV2NLyoyGO8UlreN', 'passworddigest': '08e08d87d32bea4ei05e33e789e3377b92a6udd1'}
```
`getdigest` response:
```
{'result': 0, 'expires': 'Sat, 04 Jul 2020 11:01:43 +0000', 'digest': 'pCloudpCloudpCloudZt789Bu6AADVZdco642ZYI7LYgRc8kFxf1HVHjTHTh'}
```
`get_auth_token` response:
```
{'result': 2000, 'error': 'Log in failed.'}
```

**Comment by tomgross** [comment]
Hi @qo4on thanks for the report. I never experienced such a thing. I wildly guess this is an encoding issue on Windows. I usually don't use Windows and I've never tried pCloud on Windows.
If you find out more and submit a PR I'm happy to review it.

**Comment by qo4on** [comment]
I checked [the docs](https://docs.pcloud.com/methods/intro/authentication.html):
```
string sha1 of concatenated user's password, sha1 of lowercase of username and received digest
passworddigest = sha1( password + sha1( lowercase of username ) + digest)
In both cases sha1 is presented as 40 byte hex with lowercase letters.
```
And rewrote the code as I understand it. I think now it looks a bit clearer:
```
self.username = username.lower()
self.password = password

def getdigest(self):
    resp = self._do_request("getdigest", authenticate=False)
    return resp["digest"]

passworddigest = sha1(
    (self.password + sha1(self.username.encode("utf-8")).hexdigest() + digest).encode("utf-8")
)
params = {
    "getauth": 1,
    "logout": 1,
    "username": self.username,
    "digest": digest,
    "passworddigest": passworddigest.hexdigest(),
}
```
But anyway got the same error. I have no idea what is wrong here.

**Comment by qo4on** [comment]
Actually I see the same error in Colab, Linux:
```
!pip install -U pcloud
from pcloud import PyCloud
pc = PyCloud('email@gmail.com', 'password')
```
Do I need to enable api access somewhere in the pcloud settings?

**Comment by tomgross** [comment]
Really strange 🤔 No you don't have to enable API access. It should work OOTB. Do you have non ASCII characters in your password? Can you change it temporarily to all ASCII characters and see if login works. If this is the case there is an encoding issue somewhere. This is the most probable answer I have.

**Comment by qo4on** [comment]
My login: `letters-letters@letters.letters` or in regex: `[a-z]+-[a-z]+@[a-z]+\.[a-z]+`. My password consists of numbers and English letters: `\d+[a-zA-Z]+`. I suppose they are all ASCII characters.

**Comment by tomgross** [comment]
Yes it works on a free pcloud account. I use one for testing. I really don't have a clue what could be wrong with your login. Can you authenticate with an http client, like https://httpie.org/
`http "https://api.pcloud.com/userinfo" getauth=1 logout=1 digest=pCloudpCloudpCloudZYJ8zuk9uoxhZrUv... passworddigest=08e08d...`

**Comment by qo4on** [comment]
I'm not sure how to use this `httpie`. I created a new test account:
`pc = PyCloud('atisek@yandex.com', 'sd7UY3t5m')`
It returns Authentication error on Windows and in Colab, but I can login in browser. Can you try this?

**Comment by qo4on** [comment]
I found the issue. I contacted with pcloud support and had a message from them:
> We opened EU servers few weeks ago and your account is located on them. We apologize for the inconvenience caused but the documentation is still not updated. You could try using "eapi.pcloud.com" instead of "api.pcloud.com".

I replaced `endpoint = "api.pcloud.com"` with `endpoint = "eapi.pcloud.com"` in your code and it fixed the problem. You can check it with my test account:
```
pc = PyCloud('atisek@yandex.com', 'sd7UY3t5m')
print(dir(pc))

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
...
 'userinvites',
 'username',
 'verifyemail']
```
Please update the pip version of `pycloud`.

**Comment by qo4on** [comment]
I found the issue. I contacted with pcloud support and had a message from them:
> We opened EU servers few weeks ago and your account is located on them. We apologize for the inconvenience caused but the documentation is still not updated. You could try using "eapi.pcloud.com" instead of "api.pcloud.com".

I replaced `endpoint = "api.pcloud.com"` with `endpoint = "eapi.pcloud.com"` in your code and it fixed the problem.
```
pc = PyCloud('email@gmail.com', 'password')
print(dir(pc))

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
...
 'userinvites',
 'username',
 'verifyemail']
```
Please update the pip version of `pycloud`.

**Comment by qo4on** [comment]
Can you tell what is the best way to upload many small files to one directory? Should I run:
```
pc.uploadfile(files=['/full/path/to/image1.jpg', '/Users/tom/another/image.png'],
path='/path-to-pcloud-dir')
```
in parallel (100-200 threads), or there is no need for this?

**Comment by tomgross** [comment]
Once pCloud documents this officially this needs to be changed according to the documentation. I will not change anything myself or accept PRs, since it will break other peoples authentication.

**Comment by skykiller1423** [comment]
> Я нашел проблему. Я связался с поддержкой pcloud и получил от них сообщение:
> 
> > Мы открыли серверы ЕС несколько недель назад, и ваша учетная запись находится на них. Мы приносим свои извинения за причиненные неудобства, но документация до сих пор не обновлена. Вы можете попробовать использовать «eapi.pcloud.com» вместо «api.pcloud.com».
> 
> Я заменил `endpoint = "api.pcloud.com"`с `endpoint = "eapi.pcloud.com"`в вашем коде , и это устранило проблему.
> 
> ```
> pc = PyCloud('email@gmail.com', 'password')
> print(dir(pc))
> 
> ['__class__',
>  '__delattr__',
>  '__dict__',
>  '__dir__',
> ...
>  'userinvites',
>  'username',
>  'verifyemail']
> ```
> 
> Пожалуйста, обновите версию pip `pycloud`.

Thanks!

**Comment by tomgross** [comment]
Implemented with https://github.com/tomgross/pycloud/commit/46e104020b9b01bf5d7036b2331c91042dcccfa7
