### ISSUE TITLE
raceback (most recent call last):   File "main.py", line 31, in check_update     pc.file_open(path='/SITI_BuildFirst.zip', flags=api.O_CREAT) NameError: name 'api' is not defined

### ISSUE THREAD

**Issue by skykiller1423** [tomgross/pycloud#34]
I want to make a system for updating the game, but when the update starts, it gives such an error, what should I do?)

My update code:

from pcloud import PyCloud

pc = PyCloud('my@mail.com', 'myPassword')

def check_update():
	print("Updating...")
	ui.StatusText.setText("Downloading...")
	pc.file_open(path='/SITI_BuildFirst.zip', flags=api.O_CREAT)

**Comment by tomgross** [comment]
Like you would do normaly in Python you need to import the api first `from pcloud import api`, if you intend to use it.
