### ISSUE TITLE
How to upload a remote file by simply entering the link of that file just like using the “Remote Upload” on the page？

### ISSUE THREAD

**Issue by junkesong** [tomgross/pycloud#41]
Remote Upload allows you to upload a file to pCloud from another place online by simply entering the link of that file.

How to upload a remote file by simply entering the link of that file just like using the “Remote Upload” on the page？

How to achieve the Remote Upload using python?

**Comment by tomgross** [comment]
Downloading a file to pCloud is done by the the `downloadfile` API endpoint (see https://docs.pcloud.com/methods/file/downloadfile.html). This is implemented in pCloud.
