### ISSUE TITLE
Data samples

### ISSUE THREAD

**Issue by jdrouet** [tomgross/pycloud#47]
Hi!
I'm trying to implement the binary protocol in a different language but I end up with some weird results...
Would it be possible to have some byte representation of a command and the result? Like what would be a `listfolder` with a random `auth` key? And its result?

**Comment by tomgross** [comment]
Hi @jdrouet 
I'm not associated with the pCloud company. I don't have any insights except the ones published on https://docs.pcloud.com/protocols/binary_protocol/
You'll have to dig into this yourself and/or contact the pCloud company.
