### ISSUE TITLE
pcloud.api.AuthenticationError: {'result': 2000, 'error': 'Log in failed.'}

### ISSUE THREAD

**Issue by JadeStrange** [tomgross/pycloud#49]
When I call pc = PyCloud('email@example.com', 'SecretPassword').
Is this networks problem?

**Comment by tomgross** [comment]
Hi @JadeStrange your data is most likely on an different endpoint (see https://github.com/tomgross/pycloud#usage-of-api)

If you use and ❤️ my software, consider buying me a coffee ☕ https://www.paypal.com/paypalme/tomgross42
