### ISSUE TITLE
Download file from public link

### ISSUE THREAD

**Issue by chrisdkolloff** [tomgross/pycloud#51]
Is there a way to download the content of a file via its public link? I want to access the file without having to log into my account.

Thanks!

**Comment by tomgross** [comment]
Hi @chrisdkolloff 

pCloud has a (restricted) API for handling public links. Some of the methods are only accessible with pcloud.com referrers.
There is a public method for downloading public items as zip (https://docs.pcloud.com/methods/public_links/getpubzip.html)

This method is currently not implemented in pyCloud API. You have several options:
- Implement it yourself and submit a pull request.
- Wait until I have time and interest to implement it.
- Pay me (or someone else) to implement it. My contact details are on my homepage: https://tomgross.github.io/


If you use and ❤️ my software, consider buying me a coffee ☕ https://www.paypal.com/paypalme/tomgross42

**Comment by tomgross** [comment]
Implemented for 1.0b1: https://pypi.org/project/pcloud/1.0b1/

**Comment by mrahjoo** [comment]
Thank you Tom, would you please give me a hint how to get the "code" for use with this method?

All below ways described in the website need referrer that is restricted to pcloud.com.
> The code could be obtained from:
> getfilepublink - link to a single file
> getfolderpublink - link to a folder
> gettreepublink - link to a tree
> getcollectionpublink - link to a collection

**Comment by tomgross** [comment]
Hi @mrahjoo 

Since these API calls are restricted the only way I know is to get the code from the web UI of pcloud (https://my.pcloud.com/) manually.

<img width="753" alt="Screenshot 2021-12-07 at 21 59 52" src="https://user-images.githubusercontent.com/339384/145105736-caf579cd-9035-45be-83af-87186d0b7e5d.png">
