### ISSUE TITLE
Can't use OAuth 2.0 authentication

### ISSUE THREAD

**Issue by giust** [tomgross/pycloud#54]
Hi,

I'm trying to use OAuth 2.0 authentication, but when I do the program gets stuck (it does not finish after 10 minutes). When I interrupt, I get this message:

`pc = PyCloud.oauth2_authorize(client_id=client_id, client_secret=client_secret)`
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pcloud/api.py", line 109, in oauth2_authorize
    code, hostname = TokenHandler(client_id).get_access_token()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pcloud/oauth2.py", line 44, in get_access_token
    httpServer.handle_request()
  File "/usr/lib64/python3.7/socketserver.py", line 294, in handle_request
    ready = selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

I have set the redirect URI to http://localhost:65432/, and the port is available on my machine. 

I have also tried to log in using email + password, and everything seems to work fine (using eapi endpoint).

Any idea what's going on with the OAuth 2.0 authentication?

I'm using the version 1.0b1.

Many thanks.

**Comment by giust** [comment]
Looks like it is, after I run `pc = PyCloud.oauth2_authorize(client_id=client_id, client_secret=client_secret)` it seems it listens, but nothing happens.

Running a `netstat -lntu` returns this:
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.1:65432         0.0.0.0:*               LISTEN

Do I have to manually log in somewhere or do something before I can use the method oauth2_authorize?

Some more information: I'm running this on a AWS EC2 instance (t4g) in Tokyo or ARM architecture.

**Comment by giust** [comment]
Ok, I guess I figured out what's going out. I tried to do the same process on my windows local computer, when I do it for the first time a window pops up in the explorer: https://imgur.com/a/Y2t34Gz

It's asking me to connect the application to my account. Meanwhile, the command `pc = PyCloud.oauth2_authorize(client_id=client_id, client_secret=client_secret)` is waiting, in the same way as it seems when I run it on the remote machine. Once I log in in the window that pops up, the command finishes and I can communicate with my app through the console. Then it doesn't matter if I close or reboot this machine, I don't need to log in in that window again, it connects automatically when I run `pc = PyCloud.oauth2_authorize(client_id=client_id, client_secret=client_secret)`.

I do the same test on another windows local computer, the window pops up again and I need again to log in. So it seems that everytime I'm using a new machine, I have to do that manual process.

The remote machine runs on a Linux server, where no window can pop up in any explorer, so it seems it gets stuck but I'm guessing it's waiting for me to approve the connection, in the same way it was waiting for me to approve on my windows local computer. The difference is that nothing shows up, so I have no clue how I can continue.

**Comment by tomgross** [comment]
See https://github.com/tomgross/pycloud/issues/48#issuecomment-920264871

**Comment by giust** [comment]
Thanks! That comment helped me find a solution. For anyone having the same issue as me, this is what I did:

1. First I need to get the access token, in order to do so I go to https://my.pcloud.com/oauth2/authorize?response_type=token&redirect_uri=http://localhost:65432/&client_id=<CLIENT_ID> using a web explorer. After a while the page won't load, but this address will show up in the top bar: http://localhost:65432/#access_token=**<ACCESS_TOKEN>**=bearer&userid=<USER_ID>&locationid=2&hostname=eapi.pcloud.com

2. I get the access token from above, then just `pc = PyCloud("", <ACCESS_TOKEN>, oauth2=True)`. For anyone in Europe, use `pc = PyCloud("", <ACCESS_TOKEN>, oauth2=True, endpoint="eapi")` or it won't work. Then you can just work as normal. As you mentioned, I can use this method to access from a headless server, so I just need to retrieve the access token once.

You can close this now if you want.

**Comment by tomgross** [comment]
Thanks for sharing the full solution!

**Comment by mabhijithn** [comment]
I believe the access token is now expiring. I use the access token as mentioned in this [comment](https://github.com/tomgross/pycloud/issues/48#issuecomment-991968193). However, I get the message:
`{'result': 2094, 'error': "Invalid 'access_token' provided."}`

Any solution?

**Comment by tomgross** [comment]
Hi @tomgross according to the pCloud API documentation it is still not expiring. (See https://docs.pcloud.com/methods/oauth_2.0/). OAuth 2.0 now is fully implemented by pcloud. You don't have to use the maanual workaround mentioned above. It is documented here: https://github.com/tomgross/pycloud#oauth-20-authentication

**Comment by tilenpirih** [comment]
> Thanks! That comment helped me find a solution. For anyone having the same issue as me, this is what I did:
> 
> 1. First I need to get the access token, in order to do so I go to https://my.pcloud.com/oauth2/authorize?response_type=token&redirect_uri=http://localhost:65432/&client_id=<CLIENT_ID> using a web explorer. After a while the page won't load, but this address will show up in the top bar: http://localhost:65432/#access_token=**<ACCESS_TOKEN>**=bearer&userid=<USER_ID>&locationid=2&hostname=eapi.pcloud.com
> 2. I get the access token from above, then just `pc = PyCloud("", <ACCESS_TOKEN>, oauth2=True)`. For anyone in Europe, use `pc = PyCloud("", <ACCESS_TOKEN>, oauth2=True, endpoint="eapi")` or it won't work. Then you can just work as normal. As you mentioned, I can use this method to access from a headless server, so I just need to retrieve the access token once.
> 
> You can close this now if you want.

awesome... that's just what I need. This solution work perfectly considering logining with oauth2 access token doesn't expire

![Image](https://github.com/user-attachments/assets/03230a88-b80f-43fb-94fc-a2b863e0683f)
