### ISSUE TITLE
Can't upload file with OAuth authentication

### ISSUE THREAD

**Issue by giust** [tomgross/pycloud#55]
Hi,

I can use OAuth authentication with `pc = PyCloud("", "LecVZx4nurbtMY1BZUkjfi7ZTyW7azxsy6SyO0j3pJXGRjIMPOdy", endpoint="eapi", oauth2=True)`. This works on some methods, such as `userinfo()` and `listfolder(folderid=0)`. However it doesn't with `uploadfile()`, I get the error `{'result': 2000, 'error': 'Log in failed.'}`. Inspecting the code it seems that the method  `uploadfile()` is using `auth_code`, which is initialized empty when using OAuth authentication. Is it possible to use `uploadfile()` with OAuth authentication?

Thanks!

**Comment by tomgross** [comment]
Fixed.
