### ISSUE TITLE
(Feature Request) Create folders that do not exist

### ISSUE THREAD

**Issue by JetSetDoritos** [tomgross/pycloud#58]
Example of current behavior: 
When uploading you specify path=/dir1/dir2/dir3/file.txt
But in your pcloud you only have /dir1/dir2
Instead of creating dir3, currently pcloud just silently doesn't do the upload.

It would be nice if pycloud could create the missing directories when uploading a file.  A different feature that could be easier to implement but still super useful is adding a method to create folders, so from the example I could create dir3 then upload the file.

My use case is I want to upload files from different days and organize them like /year/month/day

**Comment by tomgross** [comment]
Hi @JetSetDoritos 

pCloud has the endpoint [createfolderifnotexists](https://docs.pcloud.com/methods/folder/createfolderifnotexists.html), which you can call before uploading your files. It is supported by the pycloud library.

If you use and ❤️ my software, consider buying me a coffee ☕ https://www.paypal.com/paypalme/tomgross42
