### ISSUE TITLE
Downloading a file.

### ISSUE THREAD

**Issue by thisismygitrepo** [tomgross/pycloud#60]
Since full docs is missing, can I ask you to please update the README file to include a snippet of how to download a file? There is already 2 lines showing the upload, adding the download will make it `complete`.

**Comment by tomgross** [comment]
Hi @thisismygitrepo the API aims to be as close to the pCloud API as possible, which is also the case for [downloadfile](https://docs.pcloud.com/methods/file/downloadfile.html). I have no intention to duplicate the pCloud API documentation.
