### ISSUE TITLE
Need help on file download from Pcloud to Local Directory.

### ISSUE THREAD

**Issue by monish0612** [tomgross/pycloud#65]
I have uploaded a file to Pcloud. But this time, there is a requirement to download the uploaded file or download the already existing file from cloud. But I am unable to do so. So I have added the code snippet. Can you please provide a solution for it?

Code Snippet:

pc = PyCloud('email id', 'password', endpoint='eapi')

listr = pc.listfolder(folderid=0)

pc.downloadfile(url="File Download Link", path="Local Directory")

I can pay you for the solution.

**Comment by monish0612** [comment]
Any update on this request?

**Comment by tomgross** [comment]
Hi @monish0612 
I answered this question already in https://github.com/tomgross/pycloud/issues/60#issuecomment-1110118403.
Maybe the example from the tests is helpful: https://github.com/tomgross/pycloud/blob/1.0/src/pcloud/tests/test_integration.py#L43

**Comment by monish0612** [comment]
Hello Tom,

Still, I could not find out a solution for file download. Can you guide me
on how to do this? A quick zoom call? Just a 5mins of your time would be
appreciated.

**Comment by monish0612** [comment]
`listr = pc.listfolder(folderid=4553149281)
fd = pc.file_open(path=f"/ExpenseDB/expense.db", flags=O_CREAT)["fd"]
result = pc.file_read(fd=fd, count=140000)
resp = pc.downloadfile(url ="https://my.pcloud.com/#page=filemanager&folder=4553149281&tpl=folderlist" , folderid=4553149281 )`
