### ISSUE TITLE
Why is your github package called pycloud but your installed package is named pcloud?

### ISSUE THREAD

**Issue by ikwyl6** [tomgross/pycloud#70]
When I install your github package named 'pycloud', it gets installed as:

```~/.local/lib/python3.10/site-packages/```**pcloud**/

why not have it installed as:

```~/.local/lib/python3.10/site-packages/```**pycloud**/

so it matches your github name?? Would it make sense to keep it consistent?

**Comment by tomgross** [comment]
Good question 😉 . It was the intention to call it pycloud in the first place but this was taken on pypi already. In the meantime I think pcloud is the better name.

**Comment by ikwyl6** [comment]
https://pypi.org/search/?q=pycloud

There are variances of the name but nothing exactly with “pycloud” on pypi. The closest I saw was pycloud189 or pyicloud. You can probably rename it as “pycloud”..

**Comment by ikwyl6** [comment]
Would you consider chaning it to make it consistent?

**Comment by tomgross** [comment]
Renamed package on github https://github.com/tomgross/pcloud
