### ISSUE TITLE
I can't upload files

### ISSUE THREAD

**Issue by alexrios22** [tomgross/pycloud#75]
I can't upload files

`files = ['out.csv', 'vix.csv']`
`pc.uploadfile(files)`

this is the message it gives me

`ValueError: Required parameter ``data, files`` is missing.`

what does this refer to? Until yesterday I could upload files without problem

**Comment by Rounak40** [comment]
You have to do:
pc.uploadfile(files=files)
or
pc.uploadfile(files=['out.csv', 'vix.csv'])

**Comment by tomgross** [comment]
Thanks @Rounak40 for answering this.
