### ISSUE TITLE
How to download a file from parent folder

### ISSUE THREAD

**Issue by Ayush789** [tomgross/pycloud#8]
After logging in  i tried
`p.downloadfile(links = "0/chest-xray-pneumonia.zip")`
but i got the error 
`{'error': "Please provide 'url'.", 'result': 1040}`

**Comment by tomgross** [comment]
Hi @Ayush789 
Like the error message says, you need to specify the required _url_ parameter. See the API documentation: https://docs.pcloud.com/methods/file/downloadfile.html
Something like
```p.downloadfile(urls='chest-xray-pneumonia.zip')``` should download the file from root folder.
