### ISSUE TITLE
TypeError: str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by grill02** [tomgross/pycloud#9]
Hello,

I just installed and tried to use this

from pcloud import PyCloud
pc = PyCloud('<username>, '<password>'),

and I got the error

/usr/local/lib/python2.7/dist-packages/pcloud/api.pyc in __init__(self, username, password)
     46         self.password = password.encode('utf-8')
     47         self.session = requests.Session()
---> 48         self.auth_token = self.get_auth_token()
     49 
     50     def _do_request(self, method, authenticate=True, json=True, **kw):

/usr/local/lib/python2.7/dist-packages/pcloud/api.pyc in get_auth_token(self)
     68 
     69     def get_auth_token(self):
---> 70         digest = self.getdigest()
     71         passworddigest = sha1(
     72             self.password +

/usr/local/lib/python2.7/dist-packages/pcloud/api.pyc in getdigest(self)
     65     def getdigest(self):
     66         resp = self._do_request('getdigest', authenticate=False)
---> 67         return bytes(resp['digest'], 'utf-8')
     68 
     69     def get_auth_token(self):

TypeError: str() takes at most 1 argument (2 given)

-------

On trying with fs opener I got

/usr/local/lib/python2.7/dist-packages/fs/opener/registry.pyc in open_fs(self, fs_url, writeable, create, cwd, default_protocol)
    190                 create=create,
    191                 cwd=cwd,
--> 192                 default_protocol=default_protocol
    193             )
    194         return _fs

/usr/local/lib/python2.7/dist-packages/fs/opener/registry.pyc in open(self, fs_url, writeable, create, cwd, default_protocol)
    152             writeable,
    153             create,
--> 154             cwd
    155         )
    156         return open_fs, open_path

/usr/local/lib/python2.7/dist-packages/pcloud/pcloudfs.pyc in open_fs(fs_url, parse_result, writeable, create, cwd)
    166         fs = PCloudFS(
    167             username=parse_result.username,
--> 168             password=parse_result.password
    169         )
    170         if directory:

/usr/local/lib/python2.7/dist-packages/pcloud/pcloudfs.pyc in __init__(self, username, password)
     56 
     57     def __init__(self, username, password):
---> 58         super().__init__()
     59         self.pcloud = PyCloud(username, password)
     60         self._meta = {

TypeError: super() takes at least 1 argument (0 given)

**Comment by tomgross** [comment]
Hi @grill02 

Do you have a valid username / password combination in?
```
from pcloud import PyCloud
pc = PyCloud('my-username', 'my-secret-password'),
```

The line in your example looks strange ... 😕
